// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOmP5WPyDZJeIkzNg0iPNPsMkVf8EnTg',
    appId: '1:729318081419:web:2b845758b53960bac5a58e',
    messagingSenderId: '729318081419',
    projectId: 'startup2023-e6d76',
    authDomain: 'startup2023-e6d76.firebaseapp.com',
    databaseURL: 'https://startup2023-e6d76-default-rtdb.firebaseio.com',
    storageBucket: 'startup2023-e6d76.appspot.com',
    measurementId: 'G-HYV92C6H6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bBHWHGyfhpXKuPITaqAhPdZDWzXLs7A',
    appId: '1:729318081419:android:c809786a18d85450c5a58e',
    messagingSenderId: '729318081419',
    projectId: 'startup2023-e6d76',
    databaseURL: 'https://startup2023-e6d76-default-rtdb.firebaseio.com',
    storageBucket: 'startup2023-e6d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9fB4vLOVhg9PKDxzoFWdaJ5n0lfcieE',
    appId: '1:729318081419:ios:d675843871c40018c5a58e',
    messagingSenderId: '729318081419',
    projectId: 'startup2023-e6d76',
    databaseURL: 'https://startup2023-e6d76-default-rtdb.firebaseio.com',
    storageBucket: 'startup2023-e6d76.appspot.com',
    iosClientId: '729318081419-lmeeub2r09etuv6so8dcb8ufedbrd6gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStartup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO9fB4vLOVhg9PKDxzoFWdaJ5n0lfcieE',
    appId: '1:729318081419:ios:254b68733e5f269dc5a58e',
    messagingSenderId: '729318081419',
    projectId: 'startup2023-e6d76',
    databaseURL: 'https://startup2023-e6d76-default-rtdb.firebaseio.com',
    storageBucket: 'startup2023-e6d76.appspot.com',
    iosClientId: '729318081419-4sur7u627dc93nuqsif6fnjqa1npu1je.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStartup.RunnerTests',
  );
}
